post/urls.py
from django.urls import path
from .views import *

app_name='post'
urlpatterns = [
    path('',post_list,name='post_list'),
    path('new',post_new,name='post_new'),
    path('edit/<int:pk>/',post_edit,name='post_edit'),
    path('delete/<int:pk>',post_delete,name='post_delete'),
    path('like',post_like,name='post_like'),
    path('bookmark',post_bookmark,name='post_bookmark'),
    path('comment/new',comment_new,name="comment_new"),
    path('comment/detail_new',comment_detail_new,name="comment_detail_new"),
    path('comment/delete',comment_delete,name="comment_delete"),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    path('<int:pk>/',post_detail,name='post_detail'),
    path('<username>/list/detail',my_post_list,name='my_post_list')
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re
from cloudinary.models import CloudinaryField

def photo_path(instance,filename):
    from time import strftime
    from random import choice
    import string
    arr= [choice(string.ascii_letters) for _ in range(8)]
    pid=''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%y/%m/%d'), instance.author.username,pid,extension)
    
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = CloudinaryField('photo', blank=True)
    content = models.CharField(max_length=140, help_text="최대 140자 입력 가능")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField('Tag', blank=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')  # post.like_set 으로 접근 가능
    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='bookmark_user_set',
                                           through='Bookmark')  # post.like_set 으로 접근 가능
    
    
    

    class Meta:
        ordering = ['-created_at']

    # NOTE: content에서 tags를 추출하여, Tag 객체 가져오기, 신규 태그는 Tag instance 생성, 본인의 tag_set에 등록,
    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)  # NOTE: ManyToManyField 에 인스턴스 추가

    @property
    def like_count(self):
        return self.like_user_set.count()
    
    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()
    
    
    

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name
    
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = (
            ('user','post')
        )  
    

class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = (
            ('user','post')
        )  


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-id']
        
    def __str__(self):
        return self.content

post/templates/post/comment_detail_new_ajax.html
<div class="user_container-detail" id="comment-list-ajax-post{{comment.id}}">
                                <div class="user"><img src="{{comment.author.profile.picture.url}}" alt="user"></div>
                                <div class="comment">
                                    <span class="user_id">{{comment.author.profile.nickname}}</span>
                                    <span>{{comment.content}}</span>
                                    <span>
                                    {% if user == comment.author %}
                                    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
                                    {% endif %}
                                    </span>
                                    <div class="time">{{comment.created_at|timesince}} <span class="try_comment">답글 달기</span></div>
                                    <div class="icon_wrap">
                                        <div class="more_trigger">
                                            <div class="sprite_more_icon"></div>
                                        </div>
                                        <div>
                                            <div class="sprite_small_heart_icon_outline"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

post/templates/post/comment_new_ajax.html
 <div class="comment-detail" id="{{ comment.id }}">
    <div class="nick_name m_text">{{ comment.author.profile.nickname }} </div>
    <div>{{ comment.content }}</div>
    {% if user == comment.author %}
    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}" }>
    {% endif %}
</div>

post/templates/post/layout.html
{% extends "layout.html" %}

post/templates/post/post_list.html
{% extends "post/layout.html" %}
{% load static %}
{% load tags_extras %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/common.css' %}">
{% endblock %}

{% block content %}
<!-- hidden -->
    <div class="hidden_menu">
        <div class="scroll_inner">
            {% for following in user.profile.get_following %}
            <div class="user">
                <div class="thumb_img"><img src="{{ following.picture.url }}" alt="프로필사진"></div>
                <div class="id">{{following.nickname}}</div>
            </div>
            {% endfor %}
        </div>
    </div>


<!-- main -->
<section id="main_container">
            <div class="inner">
                <div class="contents_box">
                    {% for post in posts  %}
                    <article class="contents">
                        <header class="top">
                            <div class="user_container">
                                <div class="profile_img">
                                    {% if post.author.profile.picture  %}
                                    <img src="{{post.author.profile.picture.url}}" alt="프로필이미지">
                                    {% else %}
                                    <img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필이미지">
                                    {% endif %}
                                </div>
                                <div class="user_name">
                                    <div class="nick_name m_text">{{post.author.profile.nickname}}</div>
                                    <div class="country s_text">Seoul, South Korea</div>
                                </div>

                            </div>

                            <div class="sprite_more_icon" data-name="more">
                                <ul class="toggle_box">
                                    {% if post.author != user %}
                                    <li>
                                        {% if user.profile in post.author.profile.get_follower %}
                                        <input type="submit" class="follow" value="팔로우 취소" data-name="follow" name={{post.author.profile.id}}>
                                        {% else %}
                                        <input type="submit" class="follow" value="팔로우" data-name="follow" name={{post.author.profile.id}}>
                                        {% endif %}
                                    </li>
                                    {% endif %}
                                    {% if post.author == user %}
                                    <li><a href="{% url 'post:post_edit' post.pk %}" class ="post-edit"></a>수정</li>
                                    <li>
                                        <form action="{% url 'post:post_delete' post.pk %}" class="post-delete-form" method="post">
                                            {% csrf_token %}
                                            <input type="submit" class="post-delete" value="삭제">
                                        </form>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </header>

                        <div class="img_section">
                            <div class="trans_inner">
                                <div><img src="{{ post.photo.url }}" alt="visual01"></div>
                            </div>
                        </div>

                        <div class="bottom_icons">
                            <div class="left_icons">
                                <div class="heart_btn">
                                    {% if user in post.like_user_set.all %}
                                    <div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="heartbeat"></div>
                                    {% else %}
                                    <div class="sprite_heart_icon_outline" name="{{ post.id }}" data-name="heartbeat"></div>
                                    {% endif %}
                                </div>
                                <a href="{% url 'post:post_detail' post.pk %}" class="bubble">
                                    <div class="sprite_bubble_icon"></div>
                                </a>
                                <div class="sprite_share_icon" data-name="share"></div>
                            </div>
                            <div class="right_icon">
                                {% if user in post.bookmark_user_set.all %}
                                <div class="sprite_bookmark_outline on" data-name="bookmark" name="{{post.id}}"></div>
                                {% else %}
                                <div class="sprite_bookmark_outline" data-name="bookmark" name="{{post.id}}"></div>
                                {% endif %}
                            </div>
                        </div>
                         <div class="comment_container">
                            <div class="comment">
                                <div class="comment-detail">
                                    <div>{{ post | add_link | safe | linebreaksbr }}</div>
                                </div>                                
                            </div>
                            <div class="small_heart">
                                <div class="sprite_small_heart_icon_outline"></div>
                            </div>
                            
                        </div>
                        <div class="likes m_text">
                            {% if not post.like_count %}
                            {% else %}
                            <span id="like-count-{{ post.id }}">좋아요 {{ post.like_count }}개</span>
                            {% endif %}
                            {% if not post.bookmark_count %}
                            {% else %}
                            <span id="bookmark-count-{{ post.id }}">북마크 {{ post.bookmark_count }}개</span>
                            {% endif %}
                        </div>

                        <div class="comment_container">
                            <div class="comment" id="comment-list-ajax-post{{post.id}}">
                                {% for comment in post.comment_set.all %}
                                <div class="comment-detail" id="comment{{ comment.id }}">
                                    <div class="nick_name m_text">{{ comment.author.profile.nickname }} </div>
                                    <div>{{ comment.content }}</div>
                                    {% if user == comment.author %}
                                    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
                                    {% endif %}
                                </div>
                                {% endfor %}
                                
                            </div>
                            
                        </div>

                        <div class="timer">{{post.created_at|timesince}}전</div>
                        <div class="comment_field" id="add-comment-post{{post.id}}">
                            {% if user.is_authenticated %}
                            {{ comment_form }}
                            <div class="upload_btn m_text" data-name="comment" name="{{post.id}}">게시</div>
                            {% else %}
                            {{comment_form}}
                            <div class="upload_btn m_text" name="{{post.id}}" onclick="alert('댓글을 작성하려면 로그인이 필요합니다.')">게시</div>
                            {% endif %}
                        </div>
                    </article>
                    {% endfor %}
                    <div id="post_list_ajax"></div>
                    <input type="hidden" id="page" value="2">
                </div>

                <div class="side_box">
                    {% if user_profile %}
                    <div class="user_profile">
                        <div class="profile_thumb">
                            <img src="{{user_profile.picture.url}}" alt="프로필사진">
                        </div>
                        <div class="detail">
                            <div class="id m_text">{{user_profile.user}}</div>
                            <div class="ko_name">{{user_profile.nickname}}</div>
                        </div>
                    </div>
                    {% else %}
                    <div class="user_profile">
                        <div class="profile_thumb">
                            <img src="{% static 'imgs/thumb.jpeg'%}" alt="프로필사진">
                        </div>
                        <div class="detail">
                        </div>
                    </div>
                    {% endif %}
                    <article class="story">
                        <header class="story_header">
                            <div>스토리</div>
                            <div class="more">모두 보기</div>
                        </header>

                        <div class="scroll_inner">
                            {% if follow_post_list %}
                            {% for post in follow_post_list %}
                            <div class="thumb_user">
                                <div class="profile_thumb">
                                    <img src="{{ post.photo.url }}" alt="프로필사진">
                                </div>
                                <div class="detail">
                                    <div class="time">{{post.content}}</div>
                                    <div class="time">{{post.updated_at|timesince}}</div>
                                </div>
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </article>

                    <article class="recommend">
                        <header class="reco_header">
                            <div>회원님을 위한 추천</div>
                            <div class="more">모두 보기</div>
                        </header>
                        {% for post in posts %}
                        {% if post not in follow_post_list and post.author != user %}
                        <div class="thumb_user">
                            <div class="profile_thumb">
                                <img src="{{ post.photo.url }}" alt="프로필사진">
                            </div>
                            <div class="detail">
                                <div class="id">{{post.author}}</div>
                                <div class="time">{{post.content}} {{post.updated_at|timesince}}</div>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </article>
                </div>


            </div>
        </section>

{% include "post/script_ajax.html"%}
{% endblock %}

post/templates/post/post_list_ajax.html
{% load static %}

{% for post in posts  %}
                    <article class="contents">
                        <header class="top">
                            <div class="user_container">
                                <div class="profile_img">
                                    {% if post.author.profile.picture  %}
                                    <img src="{{post.author.profile.picture.url}}" alt="프로필이미지">
                                    {% else %}
                                    <img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필이미지">
                                    {% endif %}
                                </div>
                                <div class="user_name">
                                    <div class="nick_name m_text">{{post.author.profile.nickname}}</div>
                                    <div class="country s_text">Seoul, South Korea</div>
                                </div>

                            </div>

                            <div class="sprite_more_icon" data-name="more">
                                <ul class="toggle_box">
                                    {% if post.author != user %}
                                    <li>
                                        {% if user.profile in post.author.profile.get_follower %}
                                        <input type="submit" class="follow" value="팔로우 취소" data-name="follow" name={{post.author.profile.id}}>
                                        {% else %}
                                        <input type="submit" class="follow" value="팔로우" data-name="follow" name={{post.author.profile.id}}>
                                        {% endif %}
                                    </li>
                                    {% endif %}
                                    {% if post.author == user %}
                                    <li><a href="{% url 'post:post_edit' post.pk %}" class ="post-edit"></a>수정</li>
                                    <li>
                                        <form action="{% url 'post:post_delete' post.pk %}" class="post-delete-form" method="post">
                                            {% csrf_token %}
                                            <input type="submit" class="post-delete" value="삭제">
                                        </form>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </header>

                        <div class="img_section">
                            <div class="trans_inner">
                                <div><img src="{{ post.photo.url }}" alt="visual01"></div>
                            </div>
                        </div>

                        <div class="bottom_icons">
                            <div class="left_icons">
                                <div class="heart_btn">
                                    {% if user in post.like_user_set.all %}
                                    <div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="heartbeat"></div>
                                    {% else %}
                                    <div class="sprite_heart_icon_outline" name="{{ post.id }}" data-name="heartbeat"></div>
                                    {% endif %}
                                </div>
                                <a href="{% url 'post:post_detail' post.pk %}" class="bubble">
                                    <div class="sprite_bubble_icon"></div>
                                </a>
                                <div class="sprite_share_icon" data-name="share"></div>
                            </div>
                            <div class="right_icon">
                                {% if user in post.bookmark_user_set.all %}
                                <div class="sprite_bookmark_outline on" data-name="bookmark" name="{{post.id}}"></div>
                                {% else %}
                                <div class="sprite_bookmark_outline" data-name="bookmark" name="{{post.id}}"></div>
                                {% endif %}
                            </div>
                        </div>
                         <div class="comment_container">
                            <div class="comment">
                                <div class="comment-detail">
                                    <div>{{ post.content }}</div>
                                </div>                                
                            </div>
                            <div class="small_heart">
                                <div class="sprite_small_heart_icon_outline"></div>
                            </div>
                            
                        </div>
                        <div class="likes m_text">
                            {% if not post.like_count %}
                            {% else %}
                            <span id="like-count-{{ post.id }}">좋아요 {{ post.like_count }}개</span>
                            {% endif %}
                            {% if not post.bookmark_count %}
                            {% else %}
                            <span id="bookmark-count-{{ post.id }}">북마크 {{ post.bookmark_count }}개</span>
                            {% endif %}
                        </div>

                        <div class="comment_container">
                            <div class="comment" id="comment-list-ajax-post{{post.id}}">
                                {% for comment in post.comment_set.all %}
                                <div class="comment-detail" id="comment{{ comment.id }}">
                                    <div class="nick_name m_text">{{ comment.author.profile.nickname }} </div>
                                    <div>{{ comment.content }}</div>
                                    {% if user == comment.author %}
                                    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
                                    {% endif %}
                                </div>
                                {% endfor %}
                                
                            </div>
                            
                        </div>

                        <div class="timer">{{post.created_at|timesince}}전</div>
                        <div class="comment_field" id="add-comment-post{{post.id}}">
                            {% if user.is_authenticated %}
                            {{ comment_form }}
                            <div class="upload_btn m_text" data-name="comment" name="{{post.id}}">게시</div>
                            {% else %}
                            {{ comment_form }}
                            <div class="upload_btn m_text" data-name="comment" name="{{post.id}}" onclick="alert('댓글을 작성하려면 로그인이 필요합니다.')">게시</div>
                            {% endif %}
                        </div>
                    </article>
                    {% endfor %}

post/templates/post/script_ajax.html
<script type="text/javascript">
(function(){
   const delegation = document.querySelector('.contents_box');
    
    function delegationFunc(e){
        let elem = e.target;
        
        if (elem.matches('[data-name="heartbeat"]')){
            console.log('하트!');

            var pk = elem.getAttribute('name');
            console.log(pk);

            $.ajax({
                type: "POST",
                url: "{% url 'post:post_like' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var likeCount = document.querySelector('#like-count-'+pk);
                    if (response.like_count==0){
                        likeCount.innerHTML = '';
                    }
                    else{
                        likeCount.innerHTML = '좋아요' + response.like_count + '개';
                    }
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
            
            
        }else if (elem.matches('[data-name="bookmark"]')){

            var pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'post:post_bookmark' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var bookmarkCount = document.querySelector('#bookmark-count-'+pk);
                    if (response.bookmark_count == 0){
                        bookmarkCount.innerHTML = '';
                    }
                    else{
                        bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                    }
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
        }else if(elem.matches('[data-name="comment"]')){
            console.log("댓글")
            var pk = elem.getAttribute('name');
            var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
            console.log(content)
            if (content.length >140){
                alert('댓글은 최대 140자 입력 가능합니다.')
                return;
            }
            $.ajax({
               type:"POST",
                url:"{% url 'post:comment_new' %}",
                data:{
                    'pk':pk,
                    'content':content,
                    'csrfmiddlewaretoken':'{{csrf_token}}',   
                },
                dataType:'html',
                success:function(data,textStatus,jqXHR){
                document.querySelector('#comment-list-ajax-post'+pk).insertAdjacentHTML("afterbegin",data);
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
        }else if(elem.matches('[data-name="comment_delete"]')){
            var pk=elem.getAttribute('name');
            $.ajax({
                type:"POST",
                url:"{% url 'post:comment_delete' %}",
                data:{
                    'pk':pk,
                    'csrfmiddlewaretoken':'{{csrf_token}}',
                },
                dataType:'json',
                success:function(response){
                    if(response.status){
                        document.querySelector('#comment'+pk).remove();
                    }
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
        }else if(elem.matches('[data-name="follow"]')){
            var pk=elem.getAttribute('name');
            $.ajax({
                type:'POST',
                url:'{% url "accounts:follow" %}',
                data: {
                'pk':pk,
                'csrfmiddlewaretoken':'{{csrf_token}}',
                },
                dataType:'json',
                success:function(response){
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우 취소"
                    }
                    else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우"
                    }
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
                   
            });
            
        }
        

        elem.classList.toggle('on')
    }
    const side_box = document.querySelector('.side_box');
    const header = document.querySelector('#header');
    
    function resizefunc(){
        if(pageYOffset >= 10){
            let calcWidth = (window.innerWidth*0.5)+167;
            if (side_box){
                side_box.style.left = calcWidth+'px';
            }
        }
    }
    
    function scrollfunc(){
        var scrollHeight = pageYOffset + window.innerHeight;
        var documentHeight = document.body.scrollHeight;
        
        if (pageYOffset >=10){
            header.classList.add('on');
            resizefunc();
            if (side_box){
                side_box.classList.add('on');
            }
        }else{
            header.classList.remove('on');
            if (side_box){
                side_box.classList.remove('on');
                side_box.removeAttribute('style')
            }
        }
        if (scrollHeight >= documentHeight){
            var page = document.querySelector('#page').value;
            var end_page = {{ posts.paginator.num_pages }}
            if(page>end_page){
                return
            }
            document.querySelector('#page').value = parseInt(page)+1;
            callMorePostAjax(page);
        }
    }
    
    function callMorePostAjax(page){
    var end_page = {{ posts.paginator.num_pages }}
    if (page > end_page){
        return;
    }else{
        $.ajax({
            type: 'POST',
        url: "{% url 'post:post_list' %}",
        data: {
            'page': page,
            'csrfmiddlewaretoken':'{{csrf_token}}',
        },
        dataType: 'html',
        success: addMorePostAjax,
        error: function (request, status, error) {
            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
        });
    }
}

    function addMorePostAjax(data,textStatus,jqXHR){
        let post = document.querySelector('#post_list_ajax');
        post.insertAdjacentHTML('beforeend',data);
    }




   
    window.addEventListener('resize',resizefunc);
    window.addEventListener('scroll',scrollfunc);
    delegation.addEventListener('click',delegationFunc);
})();

</script>